apiVersion: eksctl.io/v1alpha5

kind: ClusterConfig

metadata:
  name: cluster
  region: ap-south-1
  version: "1.23"

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 8
availabilityZones: ['ap-south-1']
